# Generated by Django 5.0.1 on 2024-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lectures',
            field=models.ManyToManyField(related_name='students', to='many_to_many.lecture'),
        ),
    ]
