# Generated by Django 5.0.1 on 2024-01-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test_col',
        ),
    ]
